---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      metrics:
        /janczer/procfs/entropy: {}
      publish:
        - plugin_name: "file"
          config:
            file: "/tmp/entropy_metrics.log"
